name: Krypte
image: ubuntu-14-04-x64
min_size: 1gb
config:
  #cloud-config
  users:
    - name: krypte
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  packages:
    - git
    - docker.io
  runcmd:
    - cd /home/krypte 
    - wget https://raw.githubusercontent.com/authyhack/server/master/setup.sh
    - sh setup.sh
    - wget https://raw.githubusercontent.com/authyhack/server/master/start.sh
    - sh start.sh